import { Config } from "./src/config";

export const defaultConfig: Config = {
  url: [
    "https://platform.openai.com/docs/guides/structured-outputs?api-mode=responses",
    "https://platform.openai.com/docs/guides/function-calling?api-mode=responses&example=get-weather",
    "https://platform.openai.com/docs/guides/function-calling?api-mode=responses&example=send-email",
    "https://platform.openai.com/docs/guides/function-calling?api-mode=responses&example=search-knowledge-base",
    "https://platform.openai.com/docs/guides/conversation-state?api-mode=responses",
    "https://platform.openai.com/docs/guides/tools?api-mode=responses",
    "https://platform.openai.com/docs/guides/images-vision?api-mode=responses",
    "https://platform.openai.com/docs/guides/structured-outputs?api-mode=responses&example=chain-of-thought",
    "https://platform.openai.com/docs/guides/structured-outputs?api-mode=responses&example=structured-data",
    "https://platform.openai.com/docs/guides/structured-outputs?api-mode=responses&example=ui-generation",
    "https://platform.openai.com/docs/guides/structured-outputs?api-mode=responses&example=moderation",
    "https://platform.openai.com/docs/guides/tools-web-search?api-mode=responses",
    "https://platform.openai.com/docs/guides/tools-file-search",
    "https://platform.openai.com/docs/guides/pdf-files?api-mode=responses",
    "https://platform.openai.com/docs/models",
    "https://platform.openai.com/docs/guides/reasoning?api-mode=responses",
    "https://platform.openai.com/docs/guides/flex-processing",
    "https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#event_stream_format",
    "https://platform.openai.com/docs/guides/text?api-mode=responses",
    "https://platform.openai.com/docs/guides/safety-best-practices#end-user-ids",
    "https://platform.openai.com/docs/guides/streaming-responses?api-mode=responses",
    "https://platform.openai.com/docs/quickstart?api-mode=responses",
    "https://platform.openai.com/docs/guides/images-vision?api-mode=responses&format=url",
    "https://platform.openai.com/docs/guides/images-vision?api-mode=responses&format=base64-encoded",
  ],
  match: [],
  selector: `.docs-scroll-container`,
  maxPagesToCrawl: 20000,
  outputFileName: "openai_explicit_pages_output.json",
  maxTokens: 2000000,
  waitForSelectorTimeout: 60000,
  resourceExclusions: ["image", "stylesheet", "media", "font", "other"],
};
